export type GrblSettingType = "number" | "boolean" | "mask";

export type GrblSettingGroup =
  | "General"
  | "Motion"
  | "Homing"
  | "Spindle"
  | "Axis";

export type GrblAxis = "X" | "Y" | "Z";

export interface GrblSettingMeta {
  id: string;
  code: number;
  name: string;
  description: string;
  unit?: string;
  type: GrblSettingType;
  group: GrblSettingGroup;
  axis?: GrblAxis;
  maskAxes?: GrblAxis[];
}

export const settingsCatalog: GrblSettingMeta[] = [
  {
    id: "$0",
    code: 0,
    name: "Step pulse",
    description: "Step pulse length per step.",
    unit: "μs",
    type: "number",
    group: "General",
  },
  {
    id: "$1",
    code: 1,
    name: "Step idle delay",
    description: "Delay before disabling steppers after motion.",
    unit: "ms",
    type: "number",
    group: "General",
  },
  {
    id: "$2",
    code: 2,
    name: "Step port invert",
    description: "Invert step pulse signal per axis.",
    unit: "mask",
    type: "mask",
    group: "General",
    maskAxes: ["X", "Y", "Z"],
  },
  {
    id: "$3",
    code: 3,
    name: "Direction port invert",
    description: "Invert direction signal per axis.",
    unit: "mask",
    type: "mask",
    group: "General",
    maskAxes: ["X", "Y", "Z"],
  },
  {
    id: "$4",
    code: 4,
    name: "Step enable invert",
    description: "Invert stepper enable pin.",
    type: "boolean",
    group: "General",
  },
  {
    id: "$5",
    code: 5,
    name: "Limit pins invert",
    description: "Invert limit switch inputs.",
    type: "boolean",
    group: "General",
  },
  {
    id: "$6",
    code: 6,
    name: "Probe pin invert",
    description: "Invert probe input.",
    type: "boolean",
    group: "General",
  },
  {
    id: "$10",
    code: 10,
    name: "Status report",
    description: "Select status report fields.",
    unit: "mask",
    type: "mask",
    group: "General",
  },
  {
    id: "$11",
    code: 11,
    name: "Junction deviation",
    description: "Cornering tolerance for acceleration planner.",
    unit: "mm",
    type: "number",
    group: "Motion",
  },
  {
    id: "$12",
    code: 12,
    name: "Arc tolerance",
    description: "Chordal tolerance for arc rendering.",
    unit: "mm",
    type: "number",
    group: "Motion",
  },
  {
    id: "$13",
    code: 13,
    name: "Report in inches",
    description: "Report positions in inches instead of mm.",
    type: "boolean",
    group: "General",
  },
  {
    id: "$20",
    code: 20,
    name: "Soft limits",
    description: "Enable soft limit checks.",
    type: "boolean",
    group: "General",
  },
  {
    id: "$21",
    code: 21,
    name: "Hard limits",
    description: "Enable hard limit switches.",
    type: "boolean",
    group: "General",
  },
  {
    id: "$22",
    code: 22,
    name: "Homing cycle",
    description: "Enable homing cycle on startup.",
    type: "boolean",
    group: "Homing",
  },
  {
    id: "$23",
    code: 23,
    name: "Homing direction invert",
    description: "Invert homing direction per axis.",
    unit: "mask",
    type: "mask",
    group: "Homing",
    maskAxes: ["X", "Y", "Z"],
  },
  {
    id: "$24",
    code: 24,
    name: "Homing feed",
    description: "Slow homing feed rate.",
    unit: "mm/min",
    type: "number",
    group: "Homing",
  },
  {
    id: "$25",
    code: 25,
    name: "Homing seek",
    description: "Fast homing seek rate.",
    unit: "mm/min",
    type: "number",
    group: "Homing",
  },
  {
    id: "$26",
    code: 26,
    name: "Homing debounce",
    description: "Debounce delay for homing switches.",
    unit: "ms",
    type: "number",
    group: "Homing",
  },
  {
    id: "$27",
    code: 27,
    name: "Homing pull-off",
    description: "Pull-off distance after homing.",
    unit: "mm",
    type: "number",
    group: "Homing",
  },
  {
    id: "$30",
    code: 30,
    name: "Max spindle speed",
    description: "Maximum spindle RPM for PWM scaling.",
    unit: "RPM",
    type: "number",
    group: "Spindle",
  },
  {
    id: "$31",
    code: 31,
    name: "Min spindle speed",
    description: "Minimum spindle RPM for PWM scaling.",
    unit: "RPM",
    type: "number",
    group: "Spindle",
  },
  {
    id: "$32",
    code: 32,
    name: "Laser mode",
    description: "Enable laser mode behavior.",
    type: "boolean",
    group: "Spindle",
  },
  {
    id: "$100",
    code: 100,
    name: "X steps/mm",
    description: "Steps per millimeter for X axis.",
    unit: "steps/mm",
    type: "number",
    group: "Axis",
    axis: "X",
  },
  {
    id: "$101",
    code: 101,
    name: "Y steps/mm",
    description: "Steps per millimeter for Y axis.",
    unit: "steps/mm",
    type: "number",
    group: "Axis",
    axis: "Y",
  },
  {
    id: "$102",
    code: 102,
    name: "Z steps/mm",
    description: "Steps per millimeter for Z axis.",
    unit: "steps/mm",
    type: "number",
    group: "Axis",
    axis: "Z",
  },
  {
    id: "$110",
    code: 110,
    name: "X max rate",
    description: "Maximum travel rate for X axis.",
    unit: "mm/min",
    type: "number",
    group: "Axis",
    axis: "X",
  },
  {
    id: "$111",
    code: 111,
    name: "Y max rate",
    description: "Maximum travel rate for Y axis.",
    unit: "mm/min",
    type: "number",
    group: "Axis",
    axis: "Y",
  },
  {
    id: "$112",
    code: 112,
    name: "Z max rate",
    description: "Maximum travel rate for Z axis.",
    unit: "mm/min",
    type: "number",
    group: "Axis",
    axis: "Z",
  },
  {
    id: "$120",
    code: 120,
    name: "X acceleration",
    description: "Acceleration for X axis.",
    unit: "mm/s²",
    type: "number",
    group: "Axis",
    axis: "X",
  },
  {
    id: "$121",
    code: 121,
    name: "Y acceleration",
    description: "Acceleration for Y axis.",
    unit: "mm/s²",
    type: "number",
    group: "Axis",
    axis: "Y",
  },
  {
    id: "$122",
    code: 122,
    name: "Z acceleration",
    description: "Acceleration for Z axis.",
    unit: "mm/s²",
    type: "number",
    group: "Axis",
    axis: "Z",
  },
  {
    id: "$130",
    code: 130,
    name: "X max travel",
    description: "Maximum travel distance for X axis.",
    unit: "mm",
    type: "number",
    group: "Axis",
    axis: "X",
  },
  {
    id: "$131",
    code: 131,
    name: "Y max travel",
    description: "Maximum travel distance for Y axis.",
    unit: "mm",
    type: "number",
    group: "Axis",
    axis: "Y",
  },
  {
    id: "$132",
    code: 132,
    name: "Z max travel",
    description: "Maximum travel distance for Z axis.",
    unit: "mm",
    type: "number",
    group: "Axis",
    axis: "Z",
  },
];
