image: Visual Studio 2019

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 19 x64
  - npm install

build_script:
  - npm run pack:app

artifacts:
  - path: dist\cnc-controller-setup.exe

deploy:
- provider: GitHub
  description: Draft release
  auth_token:
    secure: bX4+yRG5TU2wiUBW4BFbiuK+wzH0IBfNZFVuXVA0jTDdENvU7GUC00LRECTfLmAt
  draft: true
  on:
    branch: main
    APPVEYOR_REPO_TAG: true

test: false
