image: Visual Studio 2019

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 19 x64
  - npm install

build_script:
  - npm run pack:app

deploy:
- provider: GitHub
  description: Draft release
  auth_token:
    secure: F9LLS3TkKo/pFmBa0e7yTV0JpYdCvyBHZfR1B84cRwBI110D9sDBnEzJ77mpT5hy0UfKC0mW4Wbp4DJWokiiOQsPvhvy1C0c4Jj4lxEHzl0i3pgvvQ8dSeNK4p6YWaPV
  artifact: dist\cnc-controller-setup.exe
  draft: true
  on:
    branch: main

test: false
